extends: relaxed

ignore: |
  docker-compose.yml
  build/
  chart/
  modules-experimental/
  .playwright-cli/

rules:
  comments: disable
  document-start: disable
  line-length: disable
  truthy: disable
