sonar.projectKey=RonaldHensbergen_composable-data-stack
sonar.organization=composable-data-stack

sonar.sources=cli
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
